name: Update Professor Data

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Clone CSRankings
        run: |
          git clone --depth 1 https://github.com/emeryberger/CSRankings.git
          echo "CSRankings cloned successfully"
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install pandas
          echo "Dependencies installed"
      
      - name: Create output directory
        run: mkdir -p public/data
      
      - name: Preprocess data
        run: |
          python scripts/preprocess.py
          echo "Data preprocessing completed"
      
      - name: List generated files
        run: |
          echo "Generated data files:"
          ls -lh public/data/
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/data
          destination_dir: data
          commit_message: 'Update professor data'

